print("Dime tu primer nombre")
x=input()
x=str(x)
print("Dime tu apellido")
y=input()
y=str(y)
print("Dime tu sexo")
z=input()
z=str(z)
print("Tú eres: "+ x +" "+ y +" "+ "y tu sexo es: " + z)